"""add reminder_sent

Revision ID: 75b9b28bba1a
Revises: ffe49374d092
Create Date: 2026-06-14 19:28:32.530821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b9b28bba1a'
down_revision: Union[str, None] = 'ffe49374d092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_sent')
    # ### end Alembic commands ###
