"""Add medium priority features

Revision ID: a1bc781c7b1c
Revises: 
Create Date: 2026-06-14 19:16:52.434925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bc781c7b1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('durations_allowed', sa.JSON(), nullable=True))
    op.alter_column('schedules', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('schedules_user_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedules_user_id_fkey', 'schedules', 'users', ['user_id'], ['id'])
    op.alter_column('schedules', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('schedules', 'durations_allowed')
    # ### end Alembic commands ###
