"""Add blocked_dates and webhooks

Revision ID: ffe49374d092
Revises: a1bc781c7b1c
Create Date: 2026-06-14 19:17:01.641718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe49374d092'
down_revision: Union[str, None] = 'a1bc781c7b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
